name: Run test task

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Composer
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 11.1.1
          php_version: 8.2
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          test_suffix: ''